"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-27 16:41:40.812786
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('object_type', sa.String(length=32), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)

    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('kyb_status', sa.String(length=32), nullable=False),
    sa.Column('is_provider', sa.Boolean(), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rfqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('origin_country', sa.String(length=2), nullable=True),
    sa.Column('origin_city', sa.String(length=128), nullable=True),
    sa.Column('destination_country', sa.String(length=2), nullable=True),
    sa.Column('destination_city', sa.String(length=128), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=True),
    sa.Column('commodity', sa.String(length=255), nullable=True),
    sa.Column('hs_code', sa.String(length=16), nullable=True),
    sa.Column('cargo_class', sa.String(length=32), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('volume_cbm', sa.Float(), nullable=True),
    sa.Column('packages', sa.Integer(), nullable=True),
    sa.Column('containers', sa.String(length=64), nullable=True),
    sa.Column('incoterm', sa.String(length=8), nullable=True),
    sa.Column('ready_date', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completeness', sa.Float(), nullable=False),
    sa.Column('lead_score', sa.Float(), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('missing_fields', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rfqs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rfqs_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_rfqs_status'), ['status'], unique=False)

    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('lanes', sa.JSON(), nullable=False),
    sa.Column('modes', sa.JSON(), nullable=False),
    sa.Column('cargo_classes', sa.JSON(), nullable=False),
    sa.Column('ports', sa.JSON(), nullable=False),
    sa.Column('certifications', sa.JSON(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('suspended', sa.Boolean(), nullable=False),
    sa.Column('rfqs_dispatched', sa.Integer(), nullable=False),
    sa.Column('quotes_submitted', sa.Integer(), nullable=False),
    sa.Column('total_response_hours', sa.Float(), nullable=False),
    sa.Column('completeness_sum', sa.Float(), nullable=False),
    sa.Column('price_rank_sum', sa.Float(), nullable=False),
    sa.Column('quotes_ranked', sa.Integer(), nullable=False),
    sa.Column('bookings_won', sa.Integer(), nullable=False),
    sa.Column('bookings_completed', sa.Integer(), nullable=False),
    sa.Column('exceptions', sa.Integer(), nullable=False),
    sa.Column('compliance_issues', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('dispatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfq_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('declined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decline_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispatches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispatches_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatches_rfq_id'), ['rfq_id'], unique=False)

    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfq_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('charges', sa.JSON(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('transit_days', sa.Integer(), nullable=True),
    sa.Column('valid_until', sa.String(length=10), nullable=True),
    sa.Column('exclusions', sa.Text(), nullable=True),
    sa.Column('completeness', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('submitted_via', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotes_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotes_rfq_id'), ['rfq_id'], unique=False)

    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfq_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('milestones', sa.JSON(), nullable=False),
    sa.Column('platform_fee', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id'),
    sa.UniqueConstraint('rfq_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotes_rfq_id'))
        batch_op.drop_index(batch_op.f('ix_quotes_provider_id'))

    op.drop_table('quotes')
    with op.batch_alter_table('dispatches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispatches_rfq_id'))
        batch_op.drop_index(batch_op.f('ix_dispatches_provider_id'))

    op.drop_table('dispatches')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('providers')
    with op.batch_alter_table('rfqs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rfqs_status'))
        batch_op.drop_index(batch_op.f('ix_rfqs_reference'))

    op.drop_table('rfqs')
    op.drop_table('companies')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
