"""whatsapp conversations

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-27 16:54:32.811280
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wa_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wa_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('lang', sa.String(length=2), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('draft', sa.JSON(), nullable=False),
    sa.Column('rfq_id', sa.Integer(), nullable=True),
    sa.Column('needs_human', sa.Boolean(), nullable=False),
    sa.Column('last_inbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wa_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wa_conversations_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wa_conversations_wa_id'), ['wa_id'], unique=True)

    op.create_table('wa_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('wa_message_id', sa.String(length=128), nullable=True),
    sa.Column('sender', sa.String(length=64), nullable=False),
    sa.Column('delivery', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['wa_conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wa_message_id')
    )
    with op.batch_alter_table('wa_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wa_messages_conversation_id'), ['conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wa_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wa_messages_conversation_id'))

    op.drop_table('wa_messages')
    with op.batch_alter_table('wa_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wa_conversations_wa_id'))
        batch_op.drop_index(batch_op.f('ix_wa_conversations_updated_at'))

    op.drop_table('wa_conversations')
    # ### end Alembic commands ###
